# Generated by Django 5.2.3 on 2025-07-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoOpciones',
            fields=[
                ('conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('predefinido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'conjuntos_opciones',
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('tipo_evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('tiempo_limite', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.PROTECT, to='users.perfilusuario')),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.empresa')),
                ('tipo_evaluacion', models.ForeignKey(db_column='tipo_evaluacion', on_delete=django.db.models.deletion.PROTECT, to='surveys.tipoevaluacion')),
            ],
            options={
                'db_table': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='OpcionConjunto',
            fields=[
                ('opcion_conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(max_length=256)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('puntuaje_escala', models.IntegerField(blank=True, null=True)),
                ('numero_orden', models.IntegerField()),
                ('conjunto_opciones', models.ForeignKey(db_column='conjunto_opciones', on_delete=django.db.models.deletion.CASCADE, to='surveys.conjuntoopciones')),
            ],
            options={
                'db_table': 'opciones_conjunto',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('Abierta', 'Abierta'), ('Múltiple', 'Múltiple'), ('Escala', 'Escala'), ('Bool', 'Bool')], max_length=20)),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('activador_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('pregunta_padre', models.ForeignKey(blank=True, db_column='pregunta_padre', null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.pregunta')),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='SeccionEval',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_orden', models.IntegerField()),
                ('evaluacion', models.ForeignKey(db_column='evaluacion', on_delete=django.db.models.deletion.CASCADE, to='surveys.evaluacion')),
            ],
            options={
                'db_table': 'secciones_eval',
            },
        ),
        migrations.CreateModel(
            name='SeccionPregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conjunto_opciones', models.ForeignKey(blank=True, db_column='conjunto_opciones', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.conjuntoopciones')),
                ('pregunta', models.ForeignKey(db_column='pregunta', on_delete=django.db.models.deletion.CASCADE, to='surveys.pregunta')),
                ('seccion', models.ForeignKey(db_column='seccion', on_delete=django.db.models.deletion.CASCADE, to='surveys.seccioneval')),
            ],
            options={
                'db_table': 'seccion_preguntas',
                'constraints': [models.UniqueConstraint(fields=('seccion', 'pregunta'), name='unique_seccion_pregunta')],
            },
        ),
    ]
