# Generated by Django 5.2.3 on 2025-07-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('pk_question', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('pk_questionnaire', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('creation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantSurvey',
            fields=[
                ('pk_plant_survey', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participant_limit', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('evaluated_id', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.plant')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('pk_access_token', models.AutoField(primary_key=True, serialize=False)),
                ('generation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('plant_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.plantsurvey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('pk_answer', models.AutoField(primary_key=True, serialize=False)),
                ('answer_value', models.TextField()),
                ('answer_date', models.DateField()),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.accesstoken')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questionnaire'),
        ),
    ]
