# Generated by Django 5.2.4 on 2025-07-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionevaluacion',
            options={'ordering': ['-id'], 'verbose_name': 'Aplicación de Evaluación', 'verbose_name_plural': 'Aplicaciones de Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-id'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
    ]
