# Generated by Django 5.2.3 on 2025-07-30 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asignacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha exacta en que la evaluación estará disponible.', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha exacta en que la evaluación dejará de estar disponible.', verbose_name='Fecha de fin')),
                ('status', models.BooleanField(default=True, help_text='Indica si la asignación está activa actualmente.', verbose_name='¿Se encuentra activa?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('puesto', models.CharField(blank=True, help_text='Puesto del empleado evaluado en el momento de la asignación.', max_length=64, null=True, verbose_name='Puesto del empleado')),
                ('departamento', models.CharField(blank=True, help_text='Departamento del empleado evaluado en el momento de la asignación.', max_length=64, null=True, verbose_name='Departamento del empleado')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ConjuntoRespuestas',
            fields=[
                ('conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej. Escala (malo, bueno)', max_length=64, unique=True, verbose_name='Nombre del conjunto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del conjunto de respuestas', null=True, verbose_name='Descripción')),
                ('predefinido', models.BooleanField(default=False, help_text='Indica si el conjunto de opciones es predefinido del sistema.', verbose_name='¿Predefinido?')),
            ],
            options={
                'verbose_name_plural': 'Conjuntos de opciones',
                'db_table': 'conjunto_respuestas',
                'ordering': ['predefinido'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=65, unique=True)),
                ('rfc', models.CharField(max_length=16, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('logotipo', models.CharField(blank=True, max_length=128, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('tipo_evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del tipo de evaluación.', max_length=32, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de evaluación.', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos de evaluación',
                'db_table': 'tipos_evaluacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, help_text='Número de empleado', max_length=20, null=True)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido_paterno', models.CharField(max_length=64)),
                ('apellido_materno', models.CharField(blank=True, max_length=64, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('antiguedad', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.CASCADE, to='users.departamento')),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa', help_text='Empresa a la que pertenece el empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('asignacion_empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para que el empleado acceda a la evaluación.', unique=True, verbose_name='Token de acceso')),
                ('status', models.CharField(choices=[('Expirada', 'Expirada'), ('Pendiente', 'Pendiente'), ('Completada', 'Completada')], default='Pendiente', help_text='Estado actual de la asignación para el empleado.', max_length=16, verbose_name='Estado de la asignación')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(help_text='Asignación de evaluación a la que pertenece.', on_delete=django.db.models.deletion.CASCADE, to='users.asignacion', verbose_name='Asignación')),
                ('empleado', models.ForeignKey(help_text='Empleado al que se le asignó la evaluación.', on_delete=django.db.models.deletion.CASCADE, to='users.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones por empleado',
                'db_table': 'asignaciones_empleado',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('asignacion', 'empleado')},
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='empleado_evaluado',
            field=models.ForeignKey(blank=True, help_text='Empleado que será el sujeto de esta evaluación 360. Un campo obligatorio para evaluaciones 360.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_360_asignadas', to='users.empleado', verbose_name='Empleado evaluado'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la evaluación.', max_length=128, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la evaluación.', null=True, verbose_name='Descripción')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones de la evaluación.', null=True, verbose_name='Instrucciones')),
                ('tiempo_limite', models.IntegerField(blank=True, help_text='Tiempo máximo para contestar la evaluación.', null=True, verbose_name='Tiempo límite')),
                ('umbral_aprobacion', models.IntegerField(blank=True, help_text='70 (%)', null=True, verbose_name='Umbral de aprobación')),
                ('status', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Campo único de evaluaciones internas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa', verbose_name='Empresa títular')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
                'ordering': ['fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='evaluacion',
            field=models.ForeignKey(help_text='Evaluación asignada.', on_delete=django.db.models.deletion.PROTECT, to='users.evaluacion', verbose_name='Evaluación'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('apellido_paterno', models.CharField(max_length=64)),
                ('apellido_materno', models.CharField(blank=True, max_length=64, null=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nivel_usuario', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin-empresa', 'Administrador de Empresa'), ('admin-planta', 'Administrador de Planta')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('admin_empresa', models.ForeignKey(blank=True, db_column='admin_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.perfilusuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='creado_por',
            field=models.ForeignKey(help_text='Campo único de evaluaciones internas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.perfilusuario', verbose_name='Usuario creador'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='administrador',
            field=models.OneToOneField(db_column='administrador', on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario'),
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('planta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(db_column='empresa', on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
            ],
            options={
                'db_table': 'plantas',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='planta',
            field=models.ForeignKey(db_column='planta', on_delete=django.db.models.deletion.CASCADE, to='users.planta'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='planta',
            field=models.ForeignKey(db_column='planta', on_delete=django.db.models.deletion.CASCADE, to='users.planta'),
        ),
        migrations.CreateModel(
            name='PosiblesRespuestas',
            fields=[
                ('opcion_conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(help_text='Descripción/Valor de la respuesta.', max_length=256, verbose_name='Respuesta')),
                ('valor_booleano', models.BooleanField(blank=True, help_text='Valor booleano asociado a la opción.', null=True, verbose_name='Valor booleano')),
                ('valor_int', models.IntegerField(blank=True, help_text='Valor numérico asociado a la opción.', null=True, verbose_name='Valor numérico')),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor númerico decimal asociado a la opción.', max_digits=16, null=True, verbose_name='Valor decimal')),
                ('numero_orden', models.IntegerField(help_text='Orden de la opción dentro del conjunto.', verbose_name='Orden')),
                ('conjunto_respuestas', models.ForeignKey(db_column='conjunto_respuestas', help_text='Conjunto de opciones al que pertenece esta respuesta.', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='users.conjuntorespuestas', verbose_name='Conjunto de opciones')),
            ],
            options={
                'verbose_name_plural': 'Posibles respuestas',
                'db_table': 'posibles_respuestas',
                'ordering': ['conjunto_respuestas', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField(help_text='Descripción de la pregunta.', verbose_name='Pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('Abierta', 'Abierta'), ('Múltiple', 'Múltiple'), ('Escala', 'Escala'), ('Bool', 'Bool')], help_text='Define el tipo de pregunta.', max_length=20, verbose_name='Tipo de pregunta')),
                ('es_obligatoria', models.BooleanField(default=True, help_text='Define si la pregunta debe ser contestada obligatoriamente.', verbose_name='¿Es obligatoria?')),
                ('activador_padre', models.CharField(blank=True, help_text='Valor que activa esta pregunta cuando la pregunta padre es contestada.', max_length=255, null=True, verbose_name='Activador padre')),
                ('pregunta_padre', models.ForeignKey(blank=True, db_column='pregunta_padre', help_text='Pregunta de la cual esta pregunta depende.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_hijas', to='users.pregunta', verbose_name='Pregunta padre')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
                'ordering': ['pregunta_id'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('puesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.CASCADE, to='users.departamento')),
            ],
            options={
                'db_table': 'puestos',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(db_column='puesto', on_delete=django.db.models.deletion.CASCADE, to='users.puesto'),
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje total obtenido en la evaluación.', max_digits=6, null=True, verbose_name='Puntaje total')),
                ('num_respuestas_correctas', models.IntegerField(default=0, help_text='Número de respuestas correctas dadas en secciones evaluables.', verbose_name='Respuestas correctas')),
                ('num_preguntas_evaluables', models.IntegerField(default=0, help_text='Número total de preguntas en secciones evaluables con respuesta correcta definida.', verbose_name='Preguntas evaluables')),
                ('porcentaje_correctas', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de respuestas correctas sobre preguntas evaluables.', max_digits=5, null=True, verbose_name='Porcentaje correctas')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se calculó este resultado.', verbose_name='Fecha de cálculo')),
                ('aprobado', models.BooleanField(blank=True, help_text='Indica si el empleado aprobó la evaluación (según un criterio predefinido).', null=True, verbose_name='¿Aprobado?')),
                ('asignacion_empleado', models.OneToOneField(help_text='Asignación específica a la que corresponde este resultado.', on_delete=django.db.models.deletion.CASCADE, to='users.asignacionempleado', verbose_name='Asignación del Empleado')),
            ],
            options={
                'verbose_name_plural': 'Resultados de Evaluación',
                'db_table': 'resultados_evaluacion',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='SeccionEval',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la sección.', max_length=64, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la sección.', null=True, verbose_name='Descripción')),
                ('numero_orden', models.IntegerField(help_text='Número de orden dentro de la evaluación', verbose_name='Orden')),
                ('es_evaluable', models.BooleanField(default=True, help_text='Define si el contenido de esta sección es evaluable', verbose_name='¿Evaluable?')),
                ('evaluacion', models.ForeignKey(help_text='Evaluación a la que pertenece esta sección.', on_delete=django.db.models.deletion.CASCADE, to='users.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name_plural': 'Secciones',
                'db_table': 'secciones_eval',
                'ordering': ['evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='SeccionPregunta',
            fields=[
                ('seccion_pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden', models.IntegerField(help_text='Orden de la pregunta dentro de la sección.', verbose_name='Orden de la pregunta')),
                ('conjunto_respuestas', models.ForeignKey(blank=True, help_text='Conjunto de respuestas para la pregunta anteriormente seleccionada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.conjuntorespuestas', verbose_name='Conjunto de respuestas')),
                ('pregunta', models.ForeignKey(help_text='Pregunta a asignar a la sección.', on_delete=django.db.models.deletion.CASCADE, related_name='secciones_pregunta', to='users.pregunta', verbose_name='Pregunta')),
                ('respuesta_correcta', models.ForeignKey(blank=True, help_text='Opción correcta para esta pregunta en particular, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_con_respuesta_correcta', to='users.posiblesrespuestas', verbose_name='Respuesta correcta')),
                ('seccion', models.ForeignKey(help_text='Sección a la que se asigna la pregunta.', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_seccion', to='users.seccioneval', verbose_name='Sección')),
            ],
            options={
                'verbose_name_plural': 'Preguntas por sección',
                'db_table': 'seccion_preguntas',
                'ordering': ['seccion', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEmpleado',
            fields=[
                ('respuesta_empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, help_text='Respuesta de texto libre para preguntas abiertas.', null=True, verbose_name='Respuesta de texto')),
                ('respuesta_valor_numerico', models.IntegerField(blank=True, help_text='Valor numérico dado como respuesta.', null=True, verbose_name='Valor numérico')),
                ('respuesta_valor_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor decimal dado como respuesta.', max_digits=16, null=True, verbose_name='Valor decimal')),
                ('es_correcta', models.BooleanField(default=False, help_text='Indica si la respuesta dada por el empleado es la correcta.', verbose_name='¿Es correcta?')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, help_text='Fecha exacta en que se registró esta respuesta.', verbose_name='Fecha de respuesta')),
                ('asignacion_empleado', models.ForeignKey(help_text='Asignación específica a la que pertenece esta respuesta.', on_delete=django.db.models.deletion.CASCADE, to='users.asignacionempleado', verbose_name='Asignación del empleado')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, help_text='La opción predefinida que el empleado seleccionó (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.posiblesrespuestas', verbose_name='Opción seleccionada')),
                ('seccion_pregunta', models.ForeignKey(help_text='La pregunta a la que se le dio respuesta.', on_delete=django.db.models.deletion.CASCADE, to='users.seccionpregunta', verbose_name='Pregunta de la sección')),
            ],
            options={
                'verbose_name_plural': 'Respuestas de empleados',
                'db_table': 'respuestas_empleado',
                'ordering': ['asignacion_empleado', 'fecha_respuesta'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_evaluacion',
            field=models.ForeignKey(help_text='Asignación de tipo de evaluación.', on_delete=django.db.models.deletion.PROTECT, to='users.tipoevaluacion', verbose_name='Tipo de evaluación'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'planta')},
        ),
        migrations.CreateModel(
            name='AdminPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('password_temporal', models.CharField(blank=True, help_text='Contraseña temporal generada automáticamente', max_length=128, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
                ('planta', models.ForeignKey(db_column='planta_id', on_delete=django.db.models.deletion.CASCADE, to='users.planta')),
            ],
            options={
                'db_table': 'admin_plantas',
                'unique_together': {('usuario', 'planta')},
            },
        ),
        migrations.AddConstraint(
            model_name='posiblesrespuestas',
            constraint=models.UniqueConstraint(fields=('conjunto_respuestas', 'numero_orden'), name='unique_opcion_orden'),
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('nombre', 'departamento')},
        ),
        migrations.AddConstraint(
            model_name='seccioneval',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'numero_orden'), name='unique_section_orden'),
        ),
        migrations.AddConstraint(
            model_name='seccionpregunta',
            constraint=models.UniqueConstraint(fields=('seccion', 'pregunta'), name='unique_seccion_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='seccionpregunta',
            constraint=models.UniqueConstraint(fields=('seccion', 'numero_orden'), name='unique_seccion_orden'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaempleado',
            unique_together={('asignacion_empleado', 'seccion_pregunta')},
        ),
    ]
