# Generated by Django 5.2.3 on 2025-08-06 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=64, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=64, null=True, verbose_name='Apellido materno')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('nivel_usuario', models.CharField(choices=[('superadmin', 'Administrador principal'), ('admin-empresa', 'Administrador de empresa '), ('admin-planta', 'Administrador de planta')], max_length=20, verbose_name='Nivel de Usuario')),
                ('status', models.BooleanField(default=True, verbose_name='Estado de acceso a la plataforma')),
                ('admin_empresa', models.ForeignKey(blank=True, db_column='admin_empresa', help_text='Administrador de empresa que ha creado a este usuario.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario', verbose_name='Usuario creador (administrador de empresa)')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='ID del usaurio ligada a este perfil.')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['nombre', 'nivel_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=65, unique=True, verbose_name='Nombre de la empresa')),
                ('rfc', models.CharField(max_length=16, unique=True, verbose_name='RFC de la empresa')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección física de la empresa')),
                ('logotipo', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL del Logotipo')),
                ('email_contacto', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Correo electrónico de contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono de contacto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, verbose_name='¿La empresa se encuentra activa en el sistema?')),
                ('administrador', models.OneToOneField(db_column='administrador', limit_choices_to={'nivel_usuario': 'admin-empresa'}, on_delete=django.db.models.deletion.PROTECT, to='users.perfilusuario', verbose_name='Administrador de la empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('planta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre de la Planta')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('status', models.BooleanField(default=True, verbose_name='Activa')),
                ('empresa', models.ForeignKey(db_column='empresa', on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='users.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'plantas',
                'ordering': ['empresa', 'nombre', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre del departamento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.BooleanField(default=True, verbose_name='¿El departamento de esta empresa se encuentra acitvo?')),
                ('planta', models.ForeignKey(db_column='planta', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='users.planta', verbose_name='Planta')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['planta', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AdminPlanta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='¿El usuario puede administrar esta planta?')),
                ('password_temporal', models.CharField(blank=True, help_text='Contraseña temporal generada automáticamente', max_length=128, null=True, verbose_name='Contraseña temporal')),
                ('usuario', models.ForeignKey(db_column='usuario_id', limit_choices_to={'nivel_usuario': 'admin-planta'}, on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario', verbose_name='Administrador de planta')),
                ('planta', models.ForeignKey(db_column='planta_id', on_delete=django.db.models.deletion.CASCADE, to='users.planta', verbose_name='Planta asignada')),
            ],
            options={
                'verbose_name': 'Administrador de planta',
                'verbose_name_plural': 'Administradores de plantas',
                'db_table': 'admin_plantas',
                'ordering': ['planta', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('puesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre del puesto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del puesto')),
                ('status', models.BooleanField(default=True, verbose_name='¿El puesto se encuentra activo?')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='users.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=64, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=64, null=True, verbose_name='Apellido materno')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('status', models.BooleanField(default=True, verbose_name='¿El empleado se encuentra activo?')),
                ('puesto', models.ForeignKey(db_column='puesto', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='users.puesto', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['nombre', 'puesto', 'status'],
            },
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['nivel_usuario'], name='usuarios_nivel_u_7f2c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['correo'], name='usuarios_correo_ee1198_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['status'], name='usuarios_status_da3175_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nombre'], name='empresas_nombre_7f64b8_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['rfc'], name='empresas_rfc_21e5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['status'], name='empresas_status_d2abd9_idx'),
        ),
        migrations.AddIndex(
            model_name='planta',
            index=models.Index(fields=['empresa'], name='plantas_empresa_07c91e_idx'),
        ),
        migrations.AddIndex(
            model_name='planta',
            index=models.Index(fields=['status'], name='plantas_status_dd015b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planta',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['planta'], name='departament_planta_701888_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['status'], name='departament_status_df13c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('planta', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='adminplanta',
            index=models.Index(fields=['usuario'], name='admin_plant_usuario_27c511_idx'),
        ),
        migrations.AddIndex(
            model_name='adminplanta',
            index=models.Index(fields=['planta'], name='admin_plant_planta__49628a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminplanta',
            index=models.Index(fields=['status'], name='admin_plant_status_1181b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adminplanta',
            unique_together={('usuario', 'planta')},
        ),
        migrations.AddIndex(
            model_name='puesto',
            index=models.Index(fields=['departamento'], name='puestos_departa_bfea18_idx'),
        ),
        migrations.AddIndex(
            model_name='puesto',
            index=models.Index(fields=['status'], name='puestos_status_a4735b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('nombre', 'departamento')},
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['puesto'], name='empleados_puesto_db5e19_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['email'], name='empleados_email_d4f508_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['status'], name='empleados_status_0ec542_idx'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_employee_email'),
        ),
    ]
