# Generated by Django 5.2.3 on 2025-07-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_usuario',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin_empresa', 'Administrador de Empresa'), ('admin_planta', 'Administrador de Planta')], max_length=20),
        ),
    ]
