# Generated by Django 5.2.3 on 2025-07-22 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_admin_planta_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='antiguedad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='planta',
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='password_temporal',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='planta',
            field=models.ForeignKey(db_column='planta_id', on_delete=django.db.models.deletion.CASCADE, to='users.planta'),
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='planta',
            field=models.ForeignKey(db_column='planta', on_delete=django.db.models.deletion.CASCADE, to='users.planta'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(db_column='puesto', on_delete=django.db.models.deletion.CASCADE, to='users.puesto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='administrador',
            field=models.OneToOneField(db_column='administrador', on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='admin_empresa',
            field=models.ForeignKey(blank=True, db_column='admin_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planta',
            name='empresa',
            field=models.ForeignKey(db_column='empresa', on_delete=django.db.models.deletion.CASCADE, to='users.empresa'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='departamento',
            field=models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.CASCADE, to='users.departamento'),
        ),
    ]
