# Generated by Django 5.2.3 on 2025-07-05 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_perfilusuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='empresa',
            field=models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='users.empresa'),
        ),
    ]
