# Generated by Django 5.2.3 on 2025-07-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_empleado_antiguedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Salario base del puesto', max_digits=10),
        ),
    ]
