# Generated by Django 5.2.3 on 2025-07-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_planta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminplanta',
            name='password_temporal',
            field=models.CharField(blank=True, help_text='Contraseña temporal generada automáticamente', max_length=128, null=True),
        ),
    ]
