# Generated by Django 5.2.3 on 2025-07-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_adminplanta_password_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'planta')},
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('nombre', 'departamento')},
        ),
    ]
