# Generated by Django 5.2.3 on 2025-07-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_salario_to_puesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='salario',
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='password_temporal',
            field=models.CharField(blank=True, help_text='Contraseña temporal generada automáticamente', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.planta'),
        ),
        migrations.AlterField(
            model_name='adminplanta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario'),
        ),
    ]
