# Generated by Django 5.2.3 on 2025-07-30 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bd', models.CharField(default='axyomadb', max_length=100)),
                ('host', models.CharField(default='localhost', max_length=100)),
                ('puerto', models.IntegerField(default=5432)),
                ('usuario_admin', models.CharField(default='postgres', max_length=100)),
                ('directorio_respaldos', models.CharField(default='config/backups/', max_length=255)),
                ('max_respaldos_mantener', models.IntegerField(default=10)),
                ('habilitar_respaldos_automaticos', models.BooleanField(default=False)),
                ('frecuencia_respaldo_dias', models.IntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Configuración de BD',
                'verbose_name_plural': 'Configuración de BD',
            },
        ),
        migrations.CreateModel(
            name='LogRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('completo', 'Respaldo Completo'), ('parcial', 'Respaldo Parcial'), ('restauracion', 'Restauración'), ('punto_inicial', 'Restauración a Punto Inicial')], max_length=20)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_ruta', models.CharField(blank=True, max_length=500, null=True)),
                ('archivo_tamaño', models.BigIntegerField(blank=True, null=True)),
                ('tablas_incluidas', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('detalles', models.TextField(blank=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Respaldo',
                'verbose_name_plural': 'Logs de Respaldos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
