# Generated by Django 5.2.3 on 2025-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrespaldo',
            old_name='tamaño_archivo',
            new_name='archivo_tamaño',
        ),
        migrations.AddField(
            model_name='logrespaldo',
            name='archivo_ruta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logrespaldo',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logrespaldo',
            name='tipo',
            field=models.CharField(choices=[('completo', 'Respaldo Completo'), ('parcial', 'Respaldo Parcial'), ('restauracion', 'Restauración'), ('punto_inicial', 'Restauración a Punto Inicial')], max_length=20),
        ),
    ]
