# Generated by Django 5.2.3 on 2025-08-01 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoExport',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('suscripcion_id', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Fallido', 'Fallido')], max_length=20)),
                ('fecha_pago', models.DateTimeField()),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuscripcionEmpresaExport',
            fields=[
                ('suscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.IntegerField()),
                ('plan', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suscripciones_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('duracion', models.IntegerField(help_text='Duración en días', verbose_name='Duración')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Registro')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'db_table': 'planes',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionEmpresa',
            fields=[
                ('suscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(blank=True, choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], max_length=20, null=True, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Registro')),
                ('empresa', models.ForeignKey(db_column='empresa', on_delete=django.db.models.deletion.CASCADE, to='users.empresa', verbose_name='Empresa')),
                ('plan', models.ForeignKey(db_column='plan', on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plansuscripcion', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción de Empresa',
                'verbose_name_plural': 'Suscripciones de Empresas',
                'db_table': 'suscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('estado_pago', models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20, verbose_name='Estado del Pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('transaccion_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Transacción')),
                ('comprobante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprobante de Pago')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el pago')),
                ('suscripcion', models.ForeignKey(db_column='suscripcion_id', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.suscripcionempresa', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
