# Generated by Django 5.2.3 on 2025-07-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('duracion', models.IntegerField(help_text='Duración en días', verbose_name='Duración')),
                ('limite_empleados', models.IntegerField(blank=True, help_text='NULL = sin límite', null=True, verbose_name='Límite de Empleados')),
                ('limite_plantas', models.IntegerField(blank=True, help_text='NULL = sin límite', null=True, verbose_name='Límite de Plantas')),
                ('caracteristicas', models.TextField(blank=True, null=True, verbose_name='Características')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'db_table': 'planes_suscripcion',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionEmpresa',
            fields=[
                ('suscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Vencida', 'Vencida'), ('Cancelada', 'Cancelada'), ('Suspendida', 'Suspendida')], default='Activa', max_length=20, verbose_name='Estado')),
                ('status', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='users.empresa', verbose_name='Empresa')),
                ('plan_suscripcion', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plansuscripcion', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción de Empresa',
                'verbose_name_plural': 'Suscripciones de Empresas',
                'db_table': 'suscripciones_empresa',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('estado_pago', models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20, verbose_name='Estado del Pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('transaccion_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Transacción')),
                ('comprobante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprobante de Pago')),
                ('suscripcion', models.ForeignKey(db_column='suscripcion_id', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.suscripcionempresa', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
