# Generated by Django 5.2.3 on 2025-07-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_pago_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
    ]
