# Generated by Django 5.2.4 on 2025-08-02 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoRespuestas',
            fields=[
                ('conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej. Escala (malo, bueno)', max_length=64, unique=True, verbose_name='Nombre del conjunto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del conjunto de respuestas', null=True, verbose_name='Descripción')),
                ('predefinido', models.BooleanField(default=False, help_text='Indica si el conjunto de opciones es predefinido del sistema.', verbose_name='¿Predefinido?')),
            ],
            options={
                'verbose_name': 'Conjunto de respuestas',
                'verbose_name_plural': 'Conjuntos de respuestas',
                'db_table': 'conjunto_respuestas',
                'ordering': ['predefinido'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('tipo_evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del tipo de evaluación.', max_length=32, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de evaluación.', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de evaluación',
                'verbose_name_plural': 'Tipos de evaluación',
                'db_table': 'tipos_evaluacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asignacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha exacta en que la evaluación estará disponible.', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha exacta en que la evaluación dejará de estar disponible.', verbose_name='Fecha de fin')),
                ('status', models.BooleanField(default=True, help_text='Indica si la asignación está activa actualmente.', verbose_name='¿Se encuentra activa?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('puesto', models.CharField(blank=True, help_text='Puesto del empleado evaluado en el momento de la asignación.', max_length=64, null=True, verbose_name='Puesto del empleado')),
                ('departamento', models.CharField(blank=True, help_text='Departamento del empleado evaluado en el momento de la asignación.', max_length=64, null=True, verbose_name='Departamento del empleado')),
                ('empleado_evaluado', models.ForeignKey(blank=True, help_text='Empleado que será el sujeto de esta evaluación 360. Un campo obligatorio para evaluaciones 360.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_360_asignadas', to='users.empleado', verbose_name='Empleado evaluado')),
            ],
            options={
                'verbose_name': 'Asignación de evaluación',
                'verbose_name_plural': 'Asignaciones base de las evaluaciones',
                'db_table': 'asignaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('asignacion_empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para que el empleado acceda a la evaluación.', unique=True, verbose_name='Token de acceso')),
                ('status', models.CharField(choices=[('Expirada', 'Expirada'), ('Pendiente', 'Pendiente'), ('Completada', 'Completada')], default='Pendiente', help_text='Estado actual de la asignación para el empleado.', max_length=16, verbose_name='Estado de la asignación')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True)),
                ('asignacion', models.ForeignKey(help_text='Asignación de evaluación a la que pertenece.', on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.asignacion', verbose_name='Asignación')),
                ('empleado', models.ForeignKey(help_text='Empleado al que se le asignó la evaluación.', on_delete=django.db.models.deletion.CASCADE, to='users.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asignación de evaluación a empleado',
                'verbose_name_plural': 'Asignaciones de evaluaciones a empleados',
                'db_table': 'asignaciones_empleado',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('asignacion', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Nombre de la evaluación.', max_length=128, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la evaluación.', null=True, verbose_name='Descripción')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones de la evaluación.', null=True, verbose_name='Instrucciones')),
                ('contenido_informativo', models.TextField(blank=True, help_text='Enlace a información sobre la normativa.', null=True, verbose_name='Contenido informativo')),
                ('tiempo_limite', models.IntegerField(blank=True, help_text='Tiempo máximo para contestar la evaluación.', null=True, verbose_name='Tiempo límite')),
                ('umbral_aprobacion', models.IntegerField(blank=True, help_text='70 (%)', null=True, verbose_name='Umbral de aprobación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=16)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Campo único de evaluaciones internas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('empresa', models.ForeignKey(blank=True, help_text='Campo único de evaluaciones internas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa', verbose_name='Empresa títular')),
                ('tipo_evaluacion', models.ForeignKey(help_text='Asignación de tipo de evaluación.', on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.tipoevaluacion', verbose_name='Tipo de evaluación')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
                'ordering': ['fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='evaluacion',
            field=models.ForeignKey(help_text='Evaluación asignada.', on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.evaluacion', verbose_name='Evaluación'),
        ),
        migrations.CreateModel(
            name='PosiblesRespuestas',
            fields=[
                ('opcion_conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(help_text='Descripción/Valor de la respuesta.', max_length=256, verbose_name='Respuesta')),
                ('valor_booleano', models.BooleanField(blank=True, help_text='Valor booleano asociado a la opción.', null=True, verbose_name='Valor booleano')),
                ('valor_int', models.IntegerField(blank=True, help_text='Valor numérico asociado a la opción.', null=True, verbose_name='Valor numérico')),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor númerico decimal asociado a la opción.', max_digits=16, null=True, verbose_name='Valor decimal')),
                ('numero_orden', models.IntegerField(help_text='Orden de la opción dentro del conjunto.', verbose_name='Orden')),
                ('conjunto_respuestas', models.ForeignKey(db_column='conjunto_respuestas', help_text='Conjunto de opciones al que pertenece esta respuesta.', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.conjuntorespuestas', verbose_name='Conjunto de respuestas')),
            ],
            options={
                'verbose_name': 'Posible respuesta',
                'verbose_name_plural': 'Posibles respuestas',
                'db_table': 'respuestas_conjunto',
                'ordering': ['conjunto_respuestas', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField(help_text='Descripción de la pregunta.', verbose_name='Pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('abierta', 'Abierta'), ('múltiple', 'Múltiple'), ('escala', 'Escala'), ('bool', 'Bool')], default='abierta', help_text='Define el tipo de pregunta.', max_length=20, verbose_name='Tipo de pregunta')),
                ('es_obligatoria', models.BooleanField(default=True, help_text='Define si la pregunta debe ser contestada obligatoriamente.', verbose_name='¿Es obligatoria?')),
                ('activador_padre', models.CharField(blank=True, help_text='Valor que activa esta pregunta cuando la pregunta padre es contestada.', max_length=255, null=True, verbose_name='Activador padre')),
                ('pregunta_padre', models.ForeignKey(blank=True, db_column='pregunta_padre', help_text='Pregunta de la cual esta pregunta depende.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_hijas', to='evaluaciones.pregunta', verbose_name='Pregunta padre')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
                'ordering': ['pregunta_id'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje total obtenido en la evaluación.', max_digits=6, null=True, verbose_name='Puntaje total')),
                ('num_respuestas_correctas', models.IntegerField(default=0, help_text='Número de respuestas correctas dadas en secciones evaluables.', verbose_name='Respuestas correctas')),
                ('num_preguntas_evaluables', models.IntegerField(default=0, help_text='Número total de preguntas en secciones evaluables con respuesta correcta definida.', verbose_name='Preguntas evaluables')),
                ('porcentaje_correctas', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de respuestas correctas sobre preguntas evaluables.', max_digits=5, null=True, verbose_name='Porcentaje correctas')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se calculó este resultado.', verbose_name='Fecha de cálculo')),
                ('aprobado', models.BooleanField(blank=True, help_text='Indica si el empleado aprobó la evaluación (según un criterio predefinido).', null=True, verbose_name='¿Aprobado?')),
                ('asignacion_empleado', models.OneToOneField(help_text='Asignación específica a la que corresponde este resultado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.asignacionempleado', verbose_name='Asignación del empleado')),
                ('evaluacion', models.ForeignKey(help_text='Evaluación de la asignación.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Resultado de una evaluación',
                'verbose_name_plural': 'Resultados de evaluaciones',
                'db_table': 'resultados_evaluacion',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='SeccionEval',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la sección.', max_length=64, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la sección.', null=True, verbose_name='Descripción')),
                ('numero_orden', models.IntegerField(help_text='Número de orden dentro de la evaluación', verbose_name='Orden')),
                ('es_evaluable', models.BooleanField(default=True, help_text='Define si el contenido de esta sección es evaluable', verbose_name='¿Evaluable?')),
                ('evaluacion', models.ForeignKey(help_text='Evaluación a la que pertenece esta sección.', on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'secciones_eval',
                'ordering': ['evaluacion', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='SeccionPregunta',
            fields=[
                ('seccion_pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden', models.IntegerField(help_text='Orden de la pregunta dentro de la sección.', verbose_name='Orden de la pregunta')),
                ('conjunto_respuestas', models.ForeignKey(blank=True, help_text='Conjunto de respuestas para la pregunta anteriormente seleccionada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.conjuntorespuestas', verbose_name='Conjunto de respuestas')),
                ('pregunta', models.ForeignKey(help_text='Pregunta a asignar a la sección.', on_delete=django.db.models.deletion.CASCADE, related_name='secciones_pregunta', to='evaluaciones.pregunta', verbose_name='Pregunta')),
                ('respuesta_correcta', models.ForeignKey(blank=True, help_text='Opción correcta para esta pregunta en particular, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_con_respuesta_correcta', to='evaluaciones.posiblesrespuestas', verbose_name='Respuesta correcta')),
                ('seccion', models.ForeignKey(help_text='Sección a la que se asigna la pregunta.', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_seccion', to='evaluaciones.seccioneval', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Pregunta de una sección',
                'verbose_name_plural': 'Preguntas de una sección',
                'db_table': 'seccion_preguntas',
                'ordering': ['seccion', 'numero_orden'],
            },
        ),
        migrations.AddField(
            model_name='seccioneval',
            name='preguntas',
            field=models.ManyToManyField(related_name='secciones_asociadas', through='evaluaciones.SeccionPregunta', to='evaluaciones.pregunta', verbose_name='Preguntas de la sección'),
        ),
        migrations.CreateModel(
            name='RespuestaEmpleado',
            fields=[
                ('respuesta_empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, help_text='Respuesta de texto libre para preguntas abiertas.', null=True, verbose_name='Respuesta de texto')),
                ('respuesta_valor_numerico', models.IntegerField(blank=True, help_text='Valor numérico dado como respuesta.', null=True, verbose_name='Valor numérico')),
                ('respuesta_valor_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor decimal dado como respuesta.', max_digits=16, null=True, verbose_name='Valor decimal')),
                ('respuesta_valor_booleano', models.BooleanField(blank=True, help_text='Valor booleano dado como respuesta.', null=True, verbose_name='Valor booleano')),
                ('es_correcta', models.BooleanField(default=False, help_text='Indica si la respuesta dada por el empleado es la correcta.', verbose_name='¿Es correcta?')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, help_text='Fecha exacta en que se registró esta respuesta.', verbose_name='Fecha de respuesta')),
                ('asignacion_empleado', models.ForeignKey(help_text='Asignación específica a la que pertenece esta respuesta.', on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.asignacionempleado', verbose_name='Asignación del empleado')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, help_text='La opción predefinida que el empleado seleccionó (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.posiblesrespuestas', verbose_name='Opción seleccionada')),
                ('seccion_pregunta', models.ForeignKey(help_text='La pregunta a la que se le dio respuesta.', on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.seccionpregunta', verbose_name='Pregunta de la sección')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Respuestas de empleados',
                'db_table': 'respuestas_empleado',
                'ordering': ['asignacion_empleado', 'fecha_respuesta'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='secciones',
            field=models.ManyToManyField(related_name='preguntas_reutilizables', through='evaluaciones.SeccionPregunta', to='evaluaciones.seccioneval', verbose_name='Secciones de la pregunta'),
        ),
        migrations.AddConstraint(
            model_name='posiblesrespuestas',
            constraint=models.UniqueConstraint(fields=('conjunto_respuestas', 'numero_orden'), name='unique_opcion_orden'),
        ),
        migrations.AddConstraint(
            model_name='seccionpregunta',
            constraint=models.UniqueConstraint(fields=('seccion', 'pregunta'), name='unique_seccion_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='seccionpregunta',
            constraint=models.UniqueConstraint(fields=('seccion', 'numero_orden'), name='unique_seccion_orden'),
        ),
        migrations.AddConstraint(
            model_name='seccioneval',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'numero_orden'), name='unique_section_orden'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaempleado',
            unique_together={('asignacion_empleado', 'seccion_pregunta')},
        ),
    ]
