# Generated by Django 5.2.3 on 2025-08-06 10:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asignacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha en que la evaluación estará disponible', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha en que la evaluación dejará de estar disponible', verbose_name='Fecha de Fin')),
                ('status', models.BooleanField(default=True, help_text='Indica si la asignación está activa', verbose_name='Activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la asignación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('puesto_al_momento', models.CharField(blank=True, db_column='puesto_empleado', help_text='Puesto del empleado al momento de la asignación', max_length=128, null=True, verbose_name='Puesto al Momento')),
                ('departamento_al_momento', models.CharField(blank=True, db_column='departamento_empleado', help_text='Departamento del empleado al momento de la asignación', max_length=128, null=True, verbose_name='Departamento al Momento')),
                ('empleado_evaluado', models.ForeignKey(blank=True, db_column='empleado_evaluado_id', help_text='Empleado sujeto de evaluación 360 grados', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_360_asignadas', to='users.empleado', verbose_name='Empleado Evaluado')),
            ],
            options={
                'verbose_name': 'Asignación de Evaluación',
                'verbose_name_plural': 'Asignaciones de Evaluación',
                'db_table': 'asignaciones',
                'ordering': ['asignacion_id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('asignacion_empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para acceder a la evaluación', unique=True, verbose_name='Token de acceso')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Desactivada', 'Desactivada'), ('Completada', 'Completada'), ('Expirada', 'Expirada')], default='Pendiente', max_length=16, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_column='fecha_asignacion', help_text='Fecha de asignación de la evaluación al empleado', verbose_name='Fecha de Inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('asignacion', models.ForeignKey(db_column='asignacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_empleado', to='evaluaciones.asignacion', verbose_name='Asignación')),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas', to='users.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asignación de Empleado',
                'verbose_name_plural': 'Asignaciones de Empleado',
                'db_table': 'asignaciones_empleado',
                'ordering': ['asignacion_empleado_id'],
            },
        ),
        migrations.CreateModel(
            name='ConjuntoRespuestas',
            fields=[
                ('conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre identificativo del conjunto (ej: Escala Likert 5 puntos)', max_length=64, verbose_name='Nombre del Conjunto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del conjunto de respuestas', null=True, verbose_name='Descripción')),
                ('predefinido', models.BooleanField(default=False, help_text='Indica si es un conjunto del sistema que no se puede modificar', verbose_name='¿Es predefinido?')),
            ],
            options={
                'verbose_name': 'Conjunto de Respuestas',
                'verbose_name_plural': 'Conjuntos de Respuestas',
                'db_table': 'conjunto_opciones',
                'ordering': ['predefinido', 'nombre'],
                'indexes': [models.Index(fields=['nombre'], name='conjunto_op_nombre_611446_idx'), models.Index(fields=['predefinido'], name='conjunto_op_predefi_567207_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Nombre de la evaluación', max_length=128, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la evaluación', null=True, verbose_name='Descripción')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones para completar la evaluación', null=True, verbose_name='Instrucciones')),
                ('contenido_informativo', models.TextField(blank=True, help_text='Enlace a contenido informativo de la evaluación', null=True, verbose_name='Contenido informativo')),
                ('tiempo_limite', models.IntegerField(blank=True, help_text='Tiempo máximo en minutos para completar la evaluación', null=True, verbose_name='Tiempo Límite (min)')),
                ('umbral_aprobacion', models.IntegerField(blank=True, help_text='Porcentaje mínimo para aprobar (ej: 70)', null=True, verbose_name='Umbral de Aprobación (%)')),
                ('estado', models.BooleanField(default=True, verbose_name='¿La evaluación se encuentraa activa?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha en que se creó la evaluación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última fecha de ctualización')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por_id', help_text='Usuario que creó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.perfilusuario', verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', help_text='Empresa propietaria (en caso de ser Internas)', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
                'ordering': ['titulo', 'estado'],
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='evaluacion',
            field=models.ForeignKey(db_column='evaluacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='evaluaciones.evaluacion', verbose_name='Evaluación'),
        ),
        migrations.CreateModel(
            name='PosiblesRespuestas',
            fields=[
                ('opcion_conjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(help_text='Texto de la opción de respuesta', max_length=256, verbose_name='Opción')),
                ('valor_booleano', models.BooleanField(blank=True, help_text='Valor verdadero/falso asociado', null=True, verbose_name='Valor Booleano')),
                ('valor_numerico', models.IntegerField(blank=True, help_text='Valor numérico entero asociado', null=True, verbose_name='Valor Numérico')),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor numérico entero asociado', max_digits=6, null=True, verbose_name='Valor Numérico')),
                ('numero_orden', models.IntegerField(help_text='Orden de la opción dentro del conjunto', verbose_name='Orden')),
                ('conjunto_respuestas', models.ForeignKey(db_column='conjunto_respuestas', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.conjuntorespuestas', verbose_name='Conjunto de Respuestas')),
            ],
            options={
                'verbose_name': 'Opción de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
                'db_table': 'respuestas_conjunto',
                'ordering': ['conjunto_respuestas', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField(help_text='Texto de la pregunta', verbose_name='Pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('Abierta', 'Pregunta abierta'), ('Múltiple', 'Preguna con opciones'), ('Escala', 'Pregunta con escala de calificación'), ('Bool', 'Pregunta de sí/no')], help_text='Tipo de respuesta esperada', max_length=20, verbose_name='Tipo de Pregunta')),
                ('es_obligatoria', models.BooleanField(default=True, help_text='Indica si la pregunta debe ser respondida', verbose_name='¿Es obligatoria?')),
                ('activador_padre', models.CharField(blank=True, help_text='Valor que activa esta pregunta', max_length=255, null=True, verbose_name='Activador')),
                ('pregunta_padre', models.ForeignKey(blank=True, db_column='pregunta_padre', help_text='Pregunta de la cual depende esta pregunta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_hijas', to='evaluaciones.pregunta', verbose_name='Pregunta padre')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
                'ordering': ['pregunta_id'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Puntaje Total')),
                ('num_respuestas_correctas', models.IntegerField(default=0, verbose_name='Respuestas Correctas')),
                ('num_preguntas_evaluables', models.IntegerField(default=0, verbose_name='Preguntas Evaluables')),
                ('porcentaje_correctas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Aciertos')),
                ('aprobado', models.BooleanField(blank=True, null=True, verbose_name='¿Aprobado?')),
                ('asignacion_empleado', models.OneToOneField(db_column='asignacion_empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='evaluaciones.asignacionempleado', verbose_name='Asignación del empleado')),
            ],
            options={
                'verbose_name': 'Resultado de evaluación',
                'verbose_name_plural': 'Resultados de evaluación',
                'db_table': 'resultados_evaluacion',
                'ordering': ['asignacion_empleado'],
            },
        ),
        migrations.CreateModel(
            name='SeccionEval',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la sección', max_length=64, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la sección', null=True, verbose_name='Descripción')),
                ('numero_orden', models.IntegerField(help_text='Número de orden dentro de la evaluación', verbose_name='Orden')),
                ('es_evaluable', models.BooleanField(default=True, help_text='Define si las preguntas de esta sección se califican', verbose_name='¿Es evaluable?')),
                ('evaluacion', models.ForeignKey(db_column='evaluacion_id', help_text='Evaluación a la que pertenece esta sección', on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Sección de una evaluación',
                'verbose_name_plural': 'Secciones de las evaluaciones',
                'db_table': 'secciones_eval',
                'ordering': ['evaluacion', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='SeccionPregunta',
            fields=[
                ('seccion_pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden', models.IntegerField(help_text='Orden de la pregunta dentro de la sección', verbose_name='Orden en la sección')),
                ('conjunto_respuestas', models.ForeignKey(blank=True, db_column='conjunto_respuestas_id', help_text='Conjunto de opciones para esta pregunta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.conjuntorespuestas', verbose_name='Conjunto de respuestas')),
                ('pregunta', models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, related_name='secciones_pregunta', to='evaluaciones.pregunta', verbose_name='Pregunta')),
                ('respuesta_correcta', models.ForeignKey(blank=True, db_column='respuesta_correcta_id', help_text='Opción correcta para la pregunta dada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_con_respuesta_correcta', to='evaluaciones.posiblesrespuestas', verbose_name='Respuesta correcta')),
                ('seccion', models.ForeignKey(db_column='seccion_id', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_seccion', to='evaluaciones.seccioneval', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Pregunta de sección',
                'verbose_name_plural': 'Preguntas de sección',
                'db_table': 'seccion_preguntas',
                'ordering': ['seccion', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEmpleado',
            fields=[
                ('respuesta_empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, help_text='Respuesta libre para preguntas abiertas', null=True, verbose_name='Respuesta de Texto')),
                ('respuesta_valor_numerico', models.IntegerField(blank=True, null=True, verbose_name='Valor Numérico')),
                ('respuesta_valor_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Valor Decimal')),
                ('respuesta_valor_booleano', models.BooleanField(blank=True, null=True, verbose_name='Valor Booleano')),
                ('es_correcta', models.BooleanField(blank=True, help_text='Indica si la respuesta es correcta (para evaluaciones calificables)', null=True, verbose_name='¿Es correcta?')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha en que se registró la respuesta')),
                ('asignacion_empleado', models.ForeignKey(db_column='asignacion_empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.asignacionempleado', verbose_name='Asignación del empleado')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, db_column='opcion_seleccionada_id', help_text='Opción elegida de las opciones predefinidas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.posiblesrespuestas', verbose_name='Opción Seleccionada')),
                ('seccion_pregunta', models.ForeignKey(db_column='seccion_pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.seccionpregunta', verbose_name='Pregunta de la sección')),
            ],
            options={
                'verbose_name': 'Respuesta de Empleado',
                'verbose_name_plural': 'Respuestas de Empleados',
                'db_table': 'respuestas_empleado',
                'ordering': ['asignacion_empleado', 'respuesta_empleado_id'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('tipo_evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del tipo de evaluación (ej: Normativa, Interna, 360 Grados)', max_length=64, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de evaluación', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de evaluación',
                'verbose_name_plural': 'Tipos de evaluación',
                'db_table': 'tipos_evaluacion',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='tipos_evalu_nombre_b77b12_idx')],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_evaluacion',
            field=models.ForeignKey(db_column='tipo_evaluacion_id', help_text='Tipo de evaluación al que pertenece', on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.tipoevaluacion', verbose_name='Tipo de Evaluación'),
        ),
        migrations.AddIndex(
            model_name='asignacionempleado',
            index=models.Index(fields=['asignacion'], name='asignacione_asignac_6f5b11_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionempleado',
            index=models.Index(fields=['empleado'], name='asignacione_emplead_539581_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionempleado',
            index=models.Index(fields=['status'], name='asignacione_status_88ac62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionempleado',
            unique_together={('asignacion', 'empleado')},
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['evaluacion'], name='asignacione_evaluac_892cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['status'], name='asignacione_status_9a39a6_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['fecha_inicio'], name='asignacione_fecha_i_9d03ad_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['fecha_fin'], name='asignacione_fecha_f_bcae2c_idx'),
        ),
        migrations.AddIndex(
            model_name='posiblesrespuestas',
            index=models.Index(fields=['conjunto_respuestas'], name='respuestas__conjunt_c70ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='posiblesrespuestas',
            index=models.Index(fields=['numero_orden'], name='respuestas__numero__0328ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posiblesrespuestas',
            unique_together={('conjunto_respuestas', 'numero_orden')},
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['tipo_pregunta'], name='preguntas_tipo_pr_167cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['pregunta_padre'], name='preguntas_pregunt_1e9440_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoevaluacion',
            index=models.Index(fields=['asignacion_empleado'], name='resultados__asignac_4f49fd_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoevaluacion',
            index=models.Index(fields=['aprobado'], name='resultados__aprobad_a72b53_idx'),
        ),
        migrations.AddIndex(
            model_name='seccioneval',
            index=models.Index(fields=['evaluacion'], name='secciones_e_evaluac_60f6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='seccioneval',
            index=models.Index(fields=['numero_orden'], name='secciones_e_numero__7471e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seccioneval',
            unique_together={('evaluacion', 'nombre'), ('evaluacion', 'numero_orden')},
        ),
        migrations.AddIndex(
            model_name='seccionpregunta',
            index=models.Index(fields=['seccion'], name='seccion_pre_seccion_2ab1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='seccionpregunta',
            index=models.Index(fields=['pregunta'], name='seccion_pre_pregunt_857af8_idx'),
        ),
        migrations.AddIndex(
            model_name='seccionpregunta',
            index=models.Index(fields=['numero_orden'], name='seccion_pre_numero__02b236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seccionpregunta',
            unique_together={('seccion', 'numero_orden'), ('seccion', 'pregunta')},
        ),
        migrations.AddIndex(
            model_name='respuestaempleado',
            index=models.Index(fields=['asignacion_empleado'], name='respuestas__asignac_fcd0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaempleado',
            index=models.Index(fields=['seccion_pregunta'], name='respuestas__seccion_e781b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaempleado',
            unique_together={('asignacion_empleado', 'seccion_pregunta')},
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['titulo'], name='evaluacione_titulo_cf349a_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['estado'], name='evaluacione_estado_777aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['tipo_evaluacion'], name='evaluacione_tipo_ev_06eabf_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['empresa'], name='evaluacione_empresa_558431_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['creado_por'], name='evaluacione_creado__0edb36_idx'),
        ),
    ]
