# Generated by Django 5.2.4 on 2025-07-31 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Campo único de evaluaciones internas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Campo único de evaluaciones internas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa', verbose_name='Empresa títular'),
        ),
    ]
