# Generated by Django 5.2.3 on 2025-08-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
    ]
