# Generated by Django 5.2.3 on 2025-07-18 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas', to='users.empleado')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='evaluaciones.evaluacioncompleta')),
            ],
            options={
                'verbose_name': 'Asignación de Evaluación',
                'verbose_name_plural': 'Asignaciones de Evaluaciones',
                'unique_together': {('evaluacion', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='TokenEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('ip_acceso', models.GenericIPAddressField(blank=True, null=True)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='evaluaciones.asignacionevaluacion')),
            ],
            options={
                'verbose_name': 'Token de Evaluación',
                'verbose_name_plural': 'Tokens de Evaluaciones',
            },
        ),
    ]
