# Generated by Django 5.2.1 on 2025-08-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_norma', models.CharField(choices=[('NOM-035', 'NOM-035 - Factores de Riesgo Psicosocial'), ('NOM-030', 'NOM-030 - Servicios Preventivos de Seguridad')], max_length=10)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField()),
                ('tiempo_limite', models.IntegerField(blank=True, null=True)),
                ('umbral_aprobacion', models.IntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluación Oficial',
                'verbose_name_plural': 'Evaluaciones Oficiales',
                'db_table': 'evaluaciones_oficiales',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('duracion_dias', models.IntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='activa', max_length=20)),
                ('token_sesion', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('admin_asignador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.planta')),
                ('evaluacion_oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.evaluacionoficial')),
            ],
            options={
                'verbose_name': 'Asignación de Evaluación',
                'verbose_name_plural': 'Asignaciones de Evaluaciones',
                'db_table': 'asignaciones_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_empleado', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('fecha_inicio_empleado', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('progreso_porcentaje', models.IntegerField(default=0)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='evaluaciones.asignacionevaluacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleado')),
            ],
            options={
                'verbose_name': 'Empleado Asignado',
                'verbose_name_plural': 'Empleados Asignados',
                'db_table': 'empleados_asignados',
                'unique_together': {('asignacion', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='SeccionOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('numero_orden', models.IntegerField()),
                ('es_evaluable', models.BooleanField(default=True)),
                ('evaluacion_oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='evaluaciones.evaluacionoficial')),
            ],
            options={
                'verbose_name': 'Sección Oficial',
                'verbose_name_plural': 'Secciones Oficiales',
                'db_table': 'secciones_oficiales',
                'ordering': ['evaluacion_oficial', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('Múltiple', 'Opción Múltiple'), ('Abierta', 'Respuesta Abierta'), ('Si/No', 'Sí/No'), ('Escala', 'Escala Likert')], max_length=20)),
                ('opciones_respuesta', models.JSONField(blank=True, default=list)),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('numero_orden', models.IntegerField()),
                ('activador_padre', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pregunta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.preguntaoficial')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.seccionoficial')),
            ],
            options={
                'verbose_name': 'Pregunta Oficial',
                'verbose_name_plural': 'Preguntas Oficiales',
                'db_table': 'preguntas_oficiales',
                'ordering': ['seccion__evaluacion_oficial', 'seccion__numero_orden', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True)),
                ('respuesta_numerica', models.IntegerField(blank=True, null=True)),
                ('respuesta_multiple', models.JSONField(blank=True, default=list)),
                ('respuesta_booleana', models.BooleanField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('tiempo_respuesta_segundos', models.IntegerField(blank=True, null=True)),
                ('es_respuesta_final', models.BooleanField(default=True)),
                ('empleado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.empleadoasignado')),
                ('pregunta_oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.preguntaoficial')),
            ],
            options={
                'verbose_name': 'Respuesta de Empleado',
                'verbose_name_plural': 'Respuestas de Empleados',
                'db_table': 'respuestas_empleados',
                'unique_together': {('empleado_asignado', 'pregunta_oficial')},
            },
        ),
    ]
