# Generated by Django 5.2.3 on 2025-08-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_fix_creado_por_foreign_key'),
    ]

    operations = [
        # Eliminar la constraint incorrecta
        migrations.RunSQL(
            "ALTER TABLE evaluaciones DROP CONSTRAINT IF EXISTS evaluaciones_creado_por_id_0c8f3e58_fk_auth_user_id;",
            reverse_sql="-- No reverse needed"
        ),
        # Crear la constraint correcta apuntando a la tabla usuarios
        migrations.RunSQL(
            "ALTER TABLE evaluaciones ADD CONSTRAINT evaluaciones_creado_por_id_fk_usuarios FOREIGN KEY (creado_por_id) REFERENCES usuarios(id) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE evaluaciones DROP CONSTRAINT evaluaciones_creado_por_id_fk_usuarios;"
        ),
    ]
