# Generated by Django 5.2.3 on 2025-07-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_asignacionevaluacion_tokenevaluacion'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacioncompleta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_nuevas', to='users.empresa'),
        ),
    ]
