# Generated by Django 5.2.3 on 2025-07-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_alter_evaluacioncompleta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='duracion_dias',
            field=models.IntegerField(blank=True, help_text='Duración máxima en días para completar', null=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='duracion_horas',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado en horas para responder', null=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='fecha_ultimo_acceso',
            field=models.DateTimeField(blank=True, help_text='Último acceso del empleado', null=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='instrucciones_especiales',
            field=models.TextField(blank=True, help_text='Instrucciones adicionales', null=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='intentos_acceso',
            field=models.IntegerField(default=0, help_text='Número de veces que ha accedido'),
        ),
    ]
